# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='llvm_build_metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('switch', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.CharField(default='', max_length=100)),
                ('volatile', models.BooleanField(default=False)),
                ('data', models.CharField(default='', max_length=100)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
