# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llvm_config_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llvm_build_metadata',
            name='id',
        ),
        migrations.AlterField(
            model_name='llvm_build_metadata',
            name='data',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='llvm_build_metadata',
            name='switch',
            field=models.CharField(blank=True, default='', max_length=100, primary_key=True, serialize=False),
        ),
    ]
