# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llvm_config_api', '0002_auto_20160323_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llvm_build_metadata',
            name='switch',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False),
        ),
    ]
